# Generated by Django 3.2 on 2024-07-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240708_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Код подтверждения'),
        ),
    ]
